"""Export the sidecar OpenAPI schema as the Dart client's source of truth.

``backend/openapi/openapi.json`` is committed and regenerated by
``pnpm run openapi:export``. The Dart client is generated from it, and
``pnpm run openapi:check`` fails if either drifts. Generation must be
deterministic, so the token is fixed and keys are sorted.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from auto_scoring.api.app import create_app

_EXPORT_TOKEN = "openapi-export-placeholder"  # deterministic, not a real credential
SCHEMA_PATH = Path(__file__).resolve().parents[3] / "openapi" / "openapi.json"


def schema() -> dict[str, Any]:
    """Return the OpenAPI document for the sidecar app."""
    return create_app(api_token=_EXPORT_TOKEN).openapi()


def write_schema(path: Path = SCHEMA_PATH) -> None:
    """Write the schema to ``path`` with stable formatting."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(schema(), indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> None:
    write_schema()
    print(f"wrote {SCHEMA_PATH}")


if __name__ == "__main__":
    main()
