/// Colour tokens (Issue #67): the light/dark [ColorScheme]s and the
/// app-specific status colours Material has no slot for.
///
/// Two rules drive every value here. `docs/design-tokens.md` §3 records the
/// measured contrast ratios that back them, and
/// `test/app_theme_contrast_test.dart` keeps the measurements honest.
///
/// 1. **The working surface is quiet.** A grading session is hours of staring
///    at one screen, so the neutral ramp is hand-set rather than tinted by the
///    seed: an off-white that is not paper-white in light, a lifted charcoal
///    that is not black in dark. The accent families are still generated by
///    Material from [_seed] -- that machinery is what guarantees every
///    `on<Role>`/`<Role>` pair lands at a usable contrast -- but it is not
///    allowed to colour the large surfaces.
/// 2. **Saturated colour is reserved for "a human has to look at this".**
///    [AppStatusColors.attention] is the only warm, high-chroma colour in the
///    app, and it is spent on 低Confidence・要確認・OCR/AI失敗. Anything that
///    is merely *in progress* stays neutral, so progress never competes with
///    problems for the reviewer's eye.
///
/// Colour is never the only carrier of a state (Issue #25): every call site
/// pairs these with an icon and a Japanese label.
library;

import 'package:flutter/material.dart';

/// The one hue the accent families are generated from: a desaturated slate
/// blue, replacing the `#1565C0` Material-sample blue this app started with.
/// It reaches the UI only through `primary`/`secondary`/`tertiary`; the
/// neutral ramp below is overridden away from it.
const Color _seed = Color(0xFF3D6478);

/// The neutral ramp of one theme: every [ColorScheme] role that paints a
/// large area or the text on it. Grouped into their own type so the values can
/// be written without also restating the accent roles Material generates.
@immutable
class _Neutrals {
  const _Neutrals({
    required this.surface,
    required this.onSurface,
    required this.surfaceDim,
    required this.surfaceBright,
    required this.containerLowest,
    required this.containerLow,
    required this.container,
    required this.containerHigh,
    required this.containerHighest,
    required this.onSurfaceVariant,
    required this.outline,
    required this.outlineVariant,
    required this.inverseSurface,
    required this.onInverseSurface,
  });

  final Color surface;
  final Color onSurface;
  final Color surfaceDim;
  final Color surfaceBright;
  final Color containerLowest;
  final Color containerLow;
  final Color container;
  final Color containerHigh;
  final Color containerHighest;
  final Color onSurfaceVariant;
  final Color outline;
  final Color outlineVariant;
  final Color inverseSurface;
  final Color onInverseSurface;
}

/// The light ramp.
///
/// `surface` is off-white, not `#FFFFFF`: a maximum-luminance page behind
/// hours of text is the main source of glare, and the answer PDF *is* white --
/// stepping the chrome down from it also makes the sheet read as the object in
/// front.
const _Neutrals _lightNeutrals = _Neutrals(
  surface: Color(0xFFF7F8F9),
  onSurface: Color(0xFF1B1F22),
  surfaceDim: Color(0xFFD8DCDF),
  surfaceBright: Color(0xFFFDFEFE),
  containerLowest: Color(0xFFFFFFFF),
  containerLow: Color(0xFFF1F3F5),
  container: Color(0xFFEBEEF0),
  containerHigh: Color(0xFFE5E8EB),
  containerHighest: Color(0xFFDFE3E6),
  onSurfaceVariant: Color(0xFF454D52),
  outline: Color(0xFF757D83),
  outlineVariant: Color(0xFFC4CACE),
  inverseSurface: Color(0xFF2F3437),
  onInverseSurface: Color(0xFFF1F3F5),
);

/// The dark ramp. Not Material's near-black default -- two changes, both aimed
/// at the same thing, hours of Japanese text on a dark ground:
///
/// * `surface` is lifted to a charcoal. Pure black next to bright glyphs
///   maximises halation (the smear dense kanji strokes pick up at very high
///   contrast), and it leaves no room *below* `surface` for the elevation ramp.
/// * `onSurface` is a soft off-white, not `#FFFFFF`. Material's default lands
///   near 14.4:1 against its own surface; this measures 11.9:1 -- still well
///   past WCAG AAA (7:1) and noticeably calmer to read for an hour.
const _Neutrals _darkNeutrals = _Neutrals(
  surface: Color(0xFF171B1E),
  onSurface: Color(0xFFCFD7DC),
  surfaceDim: Color(0xFF171B1E),
  surfaceBright: Color(0xFF3D4448),
  containerLowest: Color(0xFF101416),
  containerLow: Color(0xFF1D2225),
  container: Color(0xFF22272B),
  containerHigh: Color(0xFF292F33),
  containerHighest: Color(0xFF30373B),
  onSurfaceVariant: Color(0xFFA8B2B8),
  outline: Color(0xFF7C868D),
  outlineVariant: Color(0xFF414951),
  inverseSurface: Color(0xFFCFD7DC),
  onInverseSurface: Color(0xFF1D2225),
);

/// The app's [ColorScheme] for [brightness].
///
/// Material generates the accent families from [_seed]; the neutral ramp is
/// then replaced wholesale by [_lightNeutrals]/[_darkNeutrals]. `surfaceTint`
/// is set to `primary` (Material's own default) but every component theme in
/// `core/app_theme.dart` sits at elevation 0, so the tint overlay never
/// actually paints -- surfaces are separated by the ramp above, not by a wash
/// of the accent hue.
ColorScheme appColorScheme(Brightness brightness) {
  final generated = ColorScheme.fromSeed(
    seedColor: _seed,
    brightness: brightness,
  );
  final neutrals = brightness == Brightness.light
      ? _lightNeutrals
      : _darkNeutrals;
  return generated.copyWith(
    surface: neutrals.surface,
    onSurface: neutrals.onSurface,
    surfaceDim: neutrals.surfaceDim,
    surfaceBright: neutrals.surfaceBright,
    surfaceContainerLowest: neutrals.containerLowest,
    surfaceContainerLow: neutrals.containerLow,
    surfaceContainer: neutrals.container,
    surfaceContainerHigh: neutrals.containerHigh,
    surfaceContainerHighest: neutrals.containerHighest,
    onSurfaceVariant: neutrals.onSurfaceVariant,
    outline: neutrals.outline,
    outlineVariant: neutrals.outlineVariant,
    inverseSurface: neutrals.inverseSurface,
    onInverseSurface: neutrals.onInverseSurface,
  );
}

/// The states this app has to show that Material's [ColorScheme] has no slot
/// for, as a [ThemeExtension] so light and dark carry their own values and
/// `Theme.of(context)` resolves them the same way it resolves `colorScheme`.
///
/// Deliberately small. There is no `info` and no `pending`: "the AI is working
/// on it" must *not* be coloured, or it would compete with the states that
/// need a person. Those use `colorScheme.onSurfaceVariant` at the call sites.
@immutable
class AppStatusColors extends ThemeExtension<AppStatusColors> {
  const AppStatusColors({
    required this.attention,
    required this.attentionContainer,
    required this.onAttentionContainer,
    required this.success,
    required this.successContainer,
    required this.onSuccessContainer,
    required this.annotationMark,
  });

  /// 「人間が確認しないと先へ進めない」の色。低Confidence・要確認・OCR/AI失敗。
  ///
  /// The only warm, high-chroma colour in the app. Distinct from
  /// `colorScheme.error`, which means *the operation failed*: a 低Confidence
  /// recognition succeeded, it just cannot be trusted unreviewed.
  final Color attention;

  /// Behind a chip or banner carrying an [attention] state.
  final Color attentionContainer;
  final Color onAttentionContainer;

  /// 「確認が済んだ」の色。承認済み設問・確認済み答案。
  ///
  /// Muted on purpose: it marks work that is *done*, and done work should
  /// recede. It is never the brightest thing on screen.
  final Color success;
  final Color successContainer;
  final Color onSuccessContainer;

  /// 添削記号(○×△・下線・囲み・点数)を答案の上に描く赤。
  ///
  /// Identical in light and dark, and that is the point: these marks are drawn
  /// over the rendered PDF page, which is white whatever theme the app is in,
  /// so they follow the paper rather than the theme. It matches the red the
  /// PDF export burns in (`backend .../pdfium_pypdf_engine.py` `_MARK_RGB`),
  /// so what a reviewer sees on screen is what the exported sheet shows.
  ///
  /// It is not `colorScheme.error`, which is what this used to borrow: a ○ on
  /// a correct answer is not an error, it is a teacher's red pen.
  final Color annotationMark;

  static const AppStatusColors light = AppStatusColors(
    attention: Color(0xFF8A5000),
    attentionContainer: Color(0xFFFFDFB4),
    onAttentionContainer: Color(0xFF2B1700),
    success: Color(0xFF2C6B41),
    successContainer: Color(0xFFC8EBD3),
    onSuccessContainer: Color(0xFF082014),
    annotationMark: _annotationMark,
  );

  static const AppStatusColors dark = AppStatusColors(
    attention: Color(0xFFFFBC63),
    attentionContainer: Color(0xFF5C3A00),
    onAttentionContainer: Color(0xFFFFDFB4),
    success: Color(0xFF88D9A2),
    successContainer: Color(0xFF16452B),
    onSuccessContainer: Color(0xFFC8EBD3),
    annotationMark: _annotationMark,
  );

  static const Color _annotationMark = Color(0xFFC62828);

  @override
  AppStatusColors copyWith({
    Color? attention,
    Color? attentionContainer,
    Color? onAttentionContainer,
    Color? success,
    Color? successContainer,
    Color? onSuccessContainer,
    Color? annotationMark,
  }) {
    return AppStatusColors(
      attention: attention ?? this.attention,
      attentionContainer: attentionContainer ?? this.attentionContainer,
      onAttentionContainer: onAttentionContainer ?? this.onAttentionContainer,
      success: success ?? this.success,
      successContainer: successContainer ?? this.successContainer,
      onSuccessContainer: onSuccessContainer ?? this.onSuccessContainer,
      annotationMark: annotationMark ?? this.annotationMark,
    );
  }

  @override
  AppStatusColors lerp(ThemeExtension<AppStatusColors>? other, double t) {
    if (other is! AppStatusColors) return this;
    return AppStatusColors(
      attention: Color.lerp(attention, other.attention, t)!,
      attentionContainer: Color.lerp(
        attentionContainer,
        other.attentionContainer,
        t,
      )!,
      onAttentionContainer: Color.lerp(
        onAttentionContainer,
        other.onAttentionContainer,
        t,
      )!,
      success: Color.lerp(success, other.success, t)!,
      successContainer: Color.lerp(
        successContainer,
        other.successContainer,
        t,
      )!,
      onSuccessContainer: Color.lerp(
        onSuccessContainer,
        other.onSuccessContainer,
        t,
      )!,
      annotationMark: Color.lerp(annotationMark, other.annotationMark, t)!,
    );
  }
}
