/// Single entry point the rest of the app uses to talk to the Python sidecar.
///
/// Innermost layer: it must not import `core` or `features` (see `AGENTS.md`
/// "Architecture" and `docs/technology-stack.md` §5 — `features -> core -> api`).
///
/// It wraps the OpenAPI-generated `auto_scoring_api` client (dio + built_value,
/// regenerated by `pnpm run openapi:generate`) and owns the cross-cutting
/// concerns the generated code leaves to callers: the per-session bearer token,
/// timeouts, cancellation, and collapsing transport failures into one
/// [SidecarApiException].
library;

import 'dart:typed_data';

import 'package:auto_scoring_api/auto_scoring_api.dart';
import 'package:dio/dio.dart';
import 'package:http_parser/http_parser.dart';

export 'package:auto_scoring_api/auto_scoring_api.dart'
    show
        AnnotationEditRequest,
        AnnotationResponse,
        BoundingBoxResponse,
        CompleteRegistrationResponse,
        CriterionOutcomeRequest,
        CriterionResultResponse,
        DependencyEdgeModel,
        DependencyGraphResponse,
        DependencyProvision,
        ExportRequestResponse,
        ExportResponse,
        GradeResultResponse,
        GradingAvailabilityResponse,
        JobResponse,
        NormalizedBBoxModel,
        NormalizedRectResponse,
        PageFormatModel,
        ProfileResponse,
        QuestionResponse,
        QuestionTextOverride,
        RecognitionResponse,
        RecognitionResponseSlim,
        RegionKind,
        RegionModel,
        ReviewActionResponse,
        ReviewResponse,
        RubricCriterionResponse,
        ScoreRequest,
        ScoreResponse,
        ScoreValueResponse,
        SubmissionResponse,
        TestResponse,
        TestSummary,
        UnresolvedQuestionModel,
        UpdateProfileRequest;
export 'package:dio/dio.dart' show CancelToken;

/// Where the sidecar is listening and the token minted for this session.
///
/// Both values come from the sidecar's startup handshake. Process supervision
/// that produces them lands with the Windows distribution work; until then this
/// is constructed by tests.
class SidecarConnection {
  const SidecarConnection({required this.baseUrl, required this.token});

  /// Origin of the sidecar, e.g. `http://127.0.0.1:52348`.
  final String baseUrl;

  /// Per-session bearer token. Never logged.
  final String token;
}

/// What went wrong with a sidecar call, once transport details are stripped.
enum SidecarErrorKind {
  /// The sidecar could not be reached (not started, wrong port, refused).
  unavailable,

  /// The request outlived its timeout.
  timeout,

  /// The caller cancelled the request via a [CancelToken].
  cancelled,

  /// The sidecar rejected the bearer token (HTTP 401).
  unauthorized,

  /// The sidecar refused a review action (HTTP 409): a stale
  /// `expected_version` (someone else already acted on this question), no AI
  /// grade to approve/edit yet, or nothing left to undo. The caller should
  /// reload this question's review history and let the reviewer retry
  /// (Issue #22 acceptance: "同時/重複requestが…古いversionの更新を拒否する").
  conflict,

  /// The sidecar answered with an error status or an unreadable body.
  badResponse,

  /// Anything else.
  unknown,
}

/// The only exception callers of [SidecarApiClient] need to handle.
class SidecarApiException implements Exception {
  SidecarApiException(
    this.kind,
    this.message, {
    this.statusCode,
    this.unconfirmedQuestionIds,
  });

  final SidecarErrorKind kind;
  final String message;
  final int? statusCode;

  /// Present only for `POST .../export`'s 409 (Issue #23 acceptance: "未確認
  /// 設問がある場合は出力を拒否し、対象を表示する") -- the question ids the
  /// sidecar reports are not yet confirmed. `null` for every other error.
  final List<String>? unconfirmedQuestionIds;

  @override
  String toString() =>
      'SidecarApiException($kind, "$message", status: $statusCode)';
}

/// Raised by [SidecarApiClient.createSubmission] when the sidecar already has
/// a submission with the same PDF content for this test (409) -- Issue #17's
/// reintake policy (docs/answer-intake-and-preprocessing.md §2). Carries the
/// existing submission id so the UI can point the user at it instead of just
/// showing a generic error.
class DuplicateSubmissionException implements Exception {
  DuplicateSubmissionException(this.message, this.existingSubmissionId);

  final String message;
  final String existingSubmissionId;

  @override
  String toString() =>
      'DuplicateSubmissionException("$message", existing: $existingSubmissionId)';
}

/// Thin, typed boundary over the generated sidecar client.
class SidecarApiClient {
  SidecarApiClient(
    SidecarConnection connection, {
    Duration timeout = const Duration(seconds: 10),
    Duration intakeTimeout = const Duration(minutes: 5),
    Dio? dio,
    Dio? uploadDio,
  }) : _dio = dio ?? Dio(),
       _uploadDio = uploadDio ?? Dio() {
    _configure(_dio, connection, timeout);
    _configure(_uploadDio, connection, intakeTimeout);
    // Pass an empty interceptor list so the generated client does not also
    // register its own auth interceptors on top of ours.
    final generated = AutoScoringApi(dio: _dio, interceptors: const []);
    _api = generated.getDefaultApi();
    _testRegistrationApi = generated.getTestRegistrationApi();
    _dependencyGraphApi = generated.getDependencyGraphApi();
    final uploadGenerated = AutoScoringApi(
      dio: _uploadDio,
      interceptors: const [],
    );
    _uploadApi = uploadGenerated.getDefaultApi();
    // Registering a test uploads two PDFs in one request, same rationale as
    // createSubmission below -- it needs the longer intake timeout, not the
    // near-instant default.
    _uploadTestRegistrationApi = uploadGenerated.getTestRegistrationApi();
    _recognitionsApi = generated.getRecognitionsApi();
    _reviewApi = generated.getReviewApi();
    _jobsApi = generated.getJobsApi();
    _exportApi = generated.getExportApi();
  }

  static void _configure(
    Dio dio,
    SidecarConnection connection,
    Duration timeout,
  ) {
    final baseUrl = _validatedLoopbackBaseUrl(connection.baseUrl);
    dio.options
      ..baseUrl = baseUrl
      ..connectTimeout = timeout
      ..sendTimeout = timeout
      ..receiveTimeout = timeout;
    dio.interceptors.add(
      InterceptorsWrapper(
        onRequest: (options, handler) {
          if (options.path != '/healthz') {
            options.headers['Authorization'] = 'Bearer ${connection.token}';
          }
          handler.next(options);
        },
      ),
    );
  }

  final Dio _dio;
  late final DefaultApi _api;
  late final TestRegistrationApi _testRegistrationApi;
  late final DependencyGraphApi _dependencyGraphApi;
  late final RecognitionsApi _recognitionsApi;
  late final ReviewApi _reviewApi;
  late final JobsApi _jobsApi;
  late final ExportApi _exportApi;

  /// A second Dio/client pair, configured with [intakeTimeout] instead of
  /// [timeout], for [createSubmission]. Rasterizing, deskewing and cropping
  /// every page of a large answer PDF happens inside that one request before
  /// the sidecar responds, so it needs far more headroom than the other
  /// (near-instant) calls share -- otherwise the client reports a timeout
  /// failure while the sidecar keeps working and commits anyway, and a
  /// client-side retry on the same bytes would then just surface as a
  /// confusing duplicate-submission conflict.
  final Dio _uploadDio;
  late final DefaultApi _uploadApi;
  late final TestRegistrationApi _uploadTestRegistrationApi;

  /// Liveness probe. Never throws: an unreachable sidecar is a state the UI
  /// renders, not an error. The endpoint itself needs no auth.
  Future<bool> isHealthy({CancelToken? cancelToken}) async {
    try {
      final response = await _api.healthzHealthzGet(cancelToken: cancelToken);
      return response.data?['status'] == 'ok';
    } on DioException {
      return false;
    }
  }

  /// Whether this installation can AI-grade at all, and if not, why
  /// (Issue #97).
  ///
  /// Answers a question no other call can: every grading job on a host with
  /// no credentials fails the same way an unreadable answer does, so without
  /// this the reviewer cannot tell "this machine cannot grade" from "the AI
  /// could not read this one". `reason` names configuration variables and
  /// host prerequisites only -- the sidecar keeps credential *values* out of
  /// it by construction (`api/app.py` の `build_ai_provider`).
  ///
  /// Throws [SidecarApiException] on any failure, like every other call here:
  /// "the sidecar did not answer" is not the same fact as "grading is
  /// unavailable", and a caller that conflated them would announce a
  /// configuration problem every time a request timed out.
  Future<GradingAvailabilityResponse> gradingAvailability({
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _api.gradingAvailabilityGradingAvailabilityGet(
        cancelToken: cancelToken,
      );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Score one answer. Throws [SidecarApiException] on any failure.
  Future<ScoreResponse> score({
    required String key,
    required int raw,
    required int maximum,
    CancelToken? cancelToken,
  }) async {
    try {
      final request = ScoreRequest(
        (builder) => builder
          ..key = key
          ..raw = raw
          ..maximum = maximum,
      );
      final response = await _api.scoreScorePost(
        scoreRequest: request,
        cancelToken: cancelToken,
      );
      final body = response.data;
      if (body == null) {
        throw SidecarApiException(
          SidecarErrorKind.badResponse,
          'sidecar returned an empty body',
          statusCode: response.statusCode,
        );
      }
      return body;
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The registered tests available to import answers into (§16.4 test picker).
  /// Throws [SidecarApiException] on any failure.
  Future<List<TestSummary>> listTests({CancelToken? cancelToken}) async {
    try {
      final response = await _api.listTestsTestsGet(cancelToken: cancelToken);
      return (response.data ?? const <TestSummary>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every submission imported for [testId], in intake order.
  /// Throws [SidecarApiException] on any failure.
  Future<List<SubmissionResponse>> listSubmissions(
    String testId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _api.listSubmissionsTestsTestIdSubmissionsGet(
        testId: testId,
        cancelToken: cancelToken,
      );
      return (response.data ?? const <SubmissionResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// One submission's current intake/processing state, for polling progress.
  /// Throws [SidecarApiException] on any failure.
  Future<SubmissionResponse> getSubmission(
    String submissionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _api.getSubmissionSubmissionsSubmissionIdGet(
        submissionId: submissionId,
        cancelToken: cancelToken,
      );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Upload one answer PDF for [testId] (§16.4 答案取込画面). Re-uploading the
  /// same failed submission retries it in place; re-uploading identical bytes
  /// for a submission that is not errored throws
  /// [DuplicateSubmissionException] instead of silently overwriting it
  /// (docs/answer-intake-and-preprocessing.md §2).
  Future<SubmissionResponse> createSubmission({
    required String testId,
    required String filePath,
    String? studentLabel,
    CancelToken? cancelToken,
  }) async {
    final MultipartFile file;
    try {
      // Explicit contentType: MultipartFile.fromFile defaults to
      // application/octet-stream when none is given, and the sidecar rejects
      // any declared content type other than application/pdf (or none at
      // all) -- left implicit, every real upload would be rejected before
      // the sidecar ever looks at the bytes.
      file = await MultipartFile.fromFile(
        filePath,
        contentType: MediaType('application', 'pdf'),
      );
    } catch (error) {
      // Reading the picked file can fail on its own (deleted, a disconnected
      // removable drive, permissions) before any request is even sent; that
      // is not a DioException, so it needs converting here too, or it would
      // reach the UI as an unhandled error instead of the retry banner every
      // other failure gets.
      throw SidecarApiException(
        SidecarErrorKind.unknown,
        'could not read the selected file: $error',
      );
    }
    try {
      final response = await _uploadApi
          .createSubmissionTestsTestIdSubmissionsPost(
            testId: testId,
            file: file,
            studentLabel: studentLabel,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      final duplicate = _duplicateSubmission(error);
      if (duplicate != null) throw duplicate;
      throw _translate(error);
    }
  }

  /// Register a new test (テスト登録画面, Issue #16): both PDFs are validated
  /// and stored, and a `draft` [TestResponse] is created. No profile exists
  /// yet -- call [analyzeProfile] next. Uses the same longer intake timeout
  /// as [createSubmission], since both PDFs are read and validated server-side
  /// before the sidecar responds.
  Future<TestResponse> createTest({
    required String name,
    String? subject,
    required String modelAnswerPath,
    required String manualPath,
    CancelToken? cancelToken,
  }) async {
    final MultipartFile modelAnswer;
    final MultipartFile manual;
    try {
      modelAnswer = await MultipartFile.fromFile(
        modelAnswerPath,
        contentType: MediaType('application', 'pdf'),
      );
      manual = await MultipartFile.fromFile(
        manualPath,
        contentType: MediaType('application', 'pdf'),
      );
    } catch (error) {
      throw SidecarApiException(
        SidecarErrorKind.unknown,
        'could not read the selected file: $error',
      );
    }
    try {
      final response = await _uploadTestRegistrationApi.createTestTestsPost(
        manual: manual,
        modelAnswer: modelAnswer,
        name: name,
        subject: subject,
        cancelToken: cancelToken,
      );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// One test's current registration state (テスト設定画面).
  /// Throws [SidecarApiException] on any failure, including 404 for an
  /// unknown [testId].
  Future<TestResponse> getTest(
    String testId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _testRegistrationApi.getTestTestsTestIdGet(
        testId: testId,
        cancelToken: cancelToken,
      );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Generate DRAFT profile candidates from [testId]'s two registration PDFs
  /// (テスト設定画面 "自動解析"/再実行). Safe to call again -- it always
  /// overwrites whatever DRAFT profile was there. Throws [SidecarApiException]
  /// (409) if the profile is already confirmed.
  ///
  /// Uses the same longer intake timeout as [createTest]/[createSubmission]:
  /// this scans up to 100 pages across both PDFs and may wait behind the
  /// sidecar's shared PDFium lock if a submission intake is already running,
  /// so the default (near-instant) timeout would fire while the server is
  /// still working -- the client would then report a failure and let the
  /// review screen re-analyze on top of a draft profile the first, still
  /// in-flight call is about to overwrite anyway.
  Future<ProfileResponse> analyzeProfile(
    String testId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _uploadTestRegistrationApi
          .analyzeProfileTestsTestIdProfileAnalyzePost(
            testId: testId,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every test regardless of status (テスト設定画面の再開導線) -- unlike
  /// [listTests], which only returns `ready` tests for the answer-intake
  /// picker, this is how a `draft` registration (its `TestSettingsPage`
  /// closed, or the app restarted) can be found and reopened again (Issue
  /// #16 review).
  Future<List<TestResponse>> listTestRegistrations({
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _testRegistrationApi
          .listTestRegistrationsTestRegistrationsGet(cancelToken: cancelToken);
      return (response.data ?? const <TestResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The current (draft or confirmed) profile for [testId].
  /// Throws [SidecarApiException] (404) if [analyzeProfile] has not run yet.
  Future<ProfileResponse> getProfile(
    String testId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _testRegistrationApi
          .getProfileTestsTestIdProfileGet(
            testId: testId,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Replace [testId]'s profile regions with a human-reviewed set (still
  /// DRAFT -- this is not the confirm step). Lets the review screen
  /// add/edit/remove regions, including fully manual ones.
  Future<ProfileResponse> updateProfile(
    String testId,
    List<RegionModel> regions, {
    CancelToken? cancelToken,
  }) async {
    try {
      final request = UpdateProfileRequest((b) => b.regions.replace(regions));
      final response = await _testRegistrationApi
          .updateProfileTestsTestIdProfilePut(
            testId: testId,
            updateProfileRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The human confirmation step over [testId]'s current profile region set
  /// (テスト設定画面 "確定"). Turns the confirmed regions into the test's
  /// real Question/Rubric rows. [revision] must match the profile currently
  /// on disk (the caller's own last `getProfile`/`updateProfile`/
  /// `analyzeProfile` response) -- otherwise another client's edit landed
  /// in between and this throws [SidecarApiException] (409), asking the
  /// caller to reload and re-review before confirming again. Also (409) if
  /// the profile is already confirmed, or (422) if the regions don't add up
  /// to a valid test (missing score, duplicate question number, ...).
  Future<ProfileResponse> confirmProfile(
    String testId, {
    required int revision,
    CancelToken? cancelToken,
  }) async {
    try {
      final request = ConfirmProfileRequest((b) => b.revision = revision);
      final response = await _testRegistrationApi
          .confirmProfileTestsTestIdProfileConfirmPost(
            testId: testId,
            confirmProfileRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The final registration gate (テスト設定画面 "登録完了"): moves [testId]
  /// from `draft` to `ready` once both the profile and the dependency graph
  /// are confirmed. Throws [SidecarApiException] (409) listing what is still
  /// missing otherwise.
  Future<CompleteRegistrationResponse> completeRegistration(
    String testId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _testRegistrationApi
          .completeRegistrationTestsTestIdCompleteRegistrationPost(
            testId: testId,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Generate a new dependency-graph candidate version for [testId] (Issue
  /// #26, shown on テスト設定画面). Always creates a new version; never
  /// overwrites one a reviewer might already be looking at.
  Future<DependencyGraphResponse> analyzeDependencyGraph(
    String testId, {
    List<QuestionTextOverride> overrides = const [],
    CancelToken? cancelToken,
  }) async {
    try {
      final request = AnalyzeRequest((b) => b.overrides.replace(overrides));
      final response = await _dependencyGraphApi
          .analyzeTestsTestIdDependencyGraphAnalyzePost(
            testId: testId,
            analyzeRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The latest dependency-graph version for [testId] (draft or confirmed).
  /// Throws [SidecarApiException] (404) if [analyzeDependencyGraph] has not
  /// run yet.
  Future<DependencyGraphResponse> getDependencyGraph(
    String testId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _dependencyGraphApi
          .getLatestTestsTestIdDependencyGraphGet(
            testId: testId,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The human confirmation step over one dependency-graph [version] of
  /// [testId]: replaces its candidate edges with the reviewer's final
  /// [edges] and locks it. [version] must be the exact version the reviewer
  /// looked at (from [getDependencyGraph]/[analyzeDependencyGraph]) -- a
  /// stale or already-confirmed version is rejected (409), as is one whose
  /// edges still contain a cycle (422).
  Future<DependencyGraphResponse> confirmDependencyGraph(
    String testId, {
    required int version,
    required List<DependencyEdgeModel> edges,
    CancelToken? cancelToken,
  }) async {
    try {
      final request = ConfirmRequest(
        (b) => b
          ..version = version
          ..edges.replace(edges),
      );
      final response = await _dependencyGraphApi
          .confirmTestsTestIdDependencyGraphConfirmPost(
            testId: testId,
            confirmRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every `Question` for [testId] (its profile areas + rubric) -- the
  /// 添削レビュー画面's Navigation Rail and Inspector (§16.5, Issue #21).
  /// Throws [SidecarApiException] (404) for an unknown [testId].
  Future<List<QuestionResponse>> listQuestions(
    String testId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _reviewApi.listQuestionsTestsTestIdQuestionsGet(
        testId: testId,
        cancelToken: cancelToken,
      );
      return (response.data ?? const <QuestionResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The original, unmodified answer PDF for [submissionId] (§13.1), for the
  /// `pdfrx` viewer to render underneath the annotation overlay. Throws
  /// [SidecarApiException] (404) if the submission or its file is missing.
  Future<Uint8List> getSourcePdf(
    String submissionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _reviewApi
          .getSourcePdfSubmissionsSubmissionIdSourcePdfGet(
            submissionId: submissionId,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every `RecognitionResult` recorded for [submissionId]/[questionId] so
  /// far, oldest first (AI proposals and human corrections, §19/§35-5).
  Future<List<RecognitionResponse>> listRecognitions(
    String submissionId,
    String questionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _recognitionsApi
          .listRecognitionsSubmissionsSubmissionIdQuestionsQuestionIdRecognitionsGet(
            submissionId: submissionId,
            questionId: questionId,
            cancelToken: cancelToken,
          );
      return (response.data ?? const <RecognitionResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every `GradeResult` recorded for [submissionId]/[questionId] so far,
  /// oldest first -- each carries its own score, Grading Confidence, rubric
  /// criteria, and rationale (§10, §19/§35-5).
  Future<List<GradeResultResponse>> listGrades(
    String submissionId,
    String questionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _reviewApi
          .listGradesSubmissionsSubmissionIdQuestionsQuestionIdGradesGet(
            submissionId: submissionId,
            questionId: questionId,
            cancelToken: cancelToken,
          );
      return (response.data ?? const <GradeResultResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every `Annotation` recorded for [submissionId]/[questionId], for the
  /// PDF overlay (§11-13).
  Future<List<AnnotationResponse>> listAnnotations(
    String submissionId,
    String questionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _reviewApi
          .listAnnotationsSubmissionsSubmissionIdQuestionsQuestionIdAnnotationsGet(
            submissionId: submissionId,
            questionId: questionId,
            cancelToken: cancelToken,
          );
      return (response.data ?? const <AnnotationResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The full append-only operation history for [submissionId]/[questionId],
  /// oldest first (Issue #22 §19). Its length is the ``expectedVersion`` the
  /// caller's *next* mutating review call for this submission-question must
  /// pass (``0`` if the list is empty).
  Future<List<ReviewResponse>> listReviews(
    String submissionId,
    String questionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _reviewApi
          .listReviewsSubmissionsSubmissionIdQuestionsQuestionIdReviewsGet(
            submissionId: submissionId,
            questionId: questionId,
            cancelToken: cancelToken,
          );
      return (response.data ?? const <ReviewResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// A human's corrected score/comment (and, optionally, recognized text and
  /// annotations) for [submissionId]/[questionId] -- always confirms in the
  /// same step (Issue #22 "edit"). [expectedVersion] must be this question's
  /// current review-history length (`listReviews(...).length`); a stale
  /// value throws [SidecarApiException] with [SidecarErrorKind.conflict].
  /// Throws the same conflict kind if no AI grade exists yet to correct, or
  /// if [expectedAiGradeId] is given and no longer names the latest AI grade
  /// (Issue #22 P1 review: a regrade completing after the reviewer's screen
  /// loaded this question's AI proposal but before this edit reached the
  /// server) -- pass the id of the AI grade currently displayed to the
  /// reviewer (`QuestionReviewState.latestAiGrade?.id`), or omit it to skip
  /// this check entirely.
  Future<ReviewActionResponse> editReview(
    String submissionId,
    String questionId, {
    required int expectedVersion,
    String? expectedAiGradeId,
    required int scoreAwarded,
    required int scoreMaximum,
    double confidence = 1.0,
    List<CriterionOutcomeRequest> criteria = const [],
    String? rationale,
    String? comment,
    String? recognizedText,
    List<AnnotationEditRequest>? annotations,
    String? note,
    CancelToken? cancelToken,
  }) async {
    try {
      final request =
          EditReviewRequest(
            (b) => b
              ..expectedVersion = expectedVersion
              ..expectedAiGradeId = expectedAiGradeId
              ..scoreAwarded = scoreAwarded
              ..scoreMaximum = scoreMaximum
              ..confidence = confidence
              ..criteria.replace(criteria)
              ..rationale = rationale
              ..comment = comment
              ..recognizedText = recognizedText
              ..note = note,
          ).rebuild(
            (b) =>
                annotations == null ? b : (b..annotations.replace(annotations)),
          );
      final response = await _reviewApi
          .editSubmissionsSubmissionIdQuestionsQuestionIdReviewEditPost(
            submissionId: submissionId,
            questionId: questionId,
            editReviewRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Records that the AI's current proposal for [submissionId]/[questionId]
  /// is unusable (Issue #22 "reject"). See [editReview] for [expectedVersion].
  Future<ReviewActionResponse> rejectReview(
    String submissionId,
    String questionId, {
    required int expectedVersion,
    String? reason,
    CancelToken? cancelToken,
  }) async {
    try {
      final request = ReasonedReviewRequest(
        (b) => b
          ..expectedVersion = expectedVersion
          ..reason = reason,
      );
      final response = await _reviewApi
          .rejectSubmissionsSubmissionIdQuestionsQuestionIdReviewRejectPost(
            submissionId: submissionId,
            questionId: questionId,
            reasonedReviewRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Queues a fresh AI attempt for [submissionId]/[questionId] (Issue #22
  /// "regrade"). See [editReview] for [expectedVersion]. The returned
  /// [ReviewActionResponse.jobId] is the freshly-queued `Job`.
  Future<ReviewActionResponse> regradeReview(
    String submissionId,
    String questionId, {
    required int expectedVersion,
    String? reason,
    CancelToken? cancelToken,
  }) async {
    try {
      final request = ReasonedReviewRequest(
        (b) => b
          ..expectedVersion = expectedVersion
          ..reason = reason,
      );
      final response = await _reviewApi
          .regradeSubmissionsSubmissionIdQuestionsQuestionIdReviewRegradePost(
            submissionId: submissionId,
            questionId: questionId,
            reasonedReviewRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Confirms the AI's current proposal for [submissionId]/[questionId] as-is
  /// (Issue #22 "approve", the confirm half of "承認して次へ" -- moving to the
  /// next question is pure client-side navigation). See [editReview] for
  /// [expectedVersion]/[expectedAiGradeId].
  Future<ReviewActionResponse> approveReview(
    String submissionId,
    String questionId, {
    required int expectedVersion,
    String? expectedAiGradeId,
    String? note,
    CancelToken? cancelToken,
  }) async {
    try {
      final request = ApproveReviewRequest(
        (b) => b
          ..expectedVersion = expectedVersion
          ..expectedAiGradeId = expectedAiGradeId
          ..note = note,
      );
      final response = await _reviewApi
          .approveSubmissionsSubmissionIdQuestionsQuestionIdReviewApprovePost(
            submissionId: submissionId,
            questionId: questionId,
            approveReviewRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Reverts the currently-effective human review action for
  /// [submissionId]/[questionId] as a *new* row (Ctrl+Z, Issue #22 "Undo") --
  /// never deletes or mutates the reverted row. See [editReview] for
  /// [expectedVersion]. Throws [SidecarApiException] with
  /// [SidecarErrorKind.conflict] if every action has already been undone (or
  /// none exists).
  Future<ReviewActionResponse> undoReview(
    String submissionId,
    String questionId, {
    required int expectedVersion,
    CancelToken? cancelToken,
  }) async {
    try {
      final request = UndoReviewRequest(
        (b) => b..expectedVersion = expectedVersion,
      );
      final response = await _reviewApi
          .undoSubmissionsSubmissionIdQuestionsQuestionIdReviewUndoPost(
            submissionId: submissionId,
            questionId: questionId,
            undoReviewRequest: request,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every `Job` (kind GRADING) ever created for [submissionId], across every
  /// question and every dependency-graph version it was submitted under
  /// (Issue #18) -- the only way to observe a per-question job's own
  /// lifecycle (queued/running/blocked/succeeded/failed/cancelled), as
  /// opposed to the submission's own coarse state (§16.5, P1 review).
  Future<List<JobResponse>> listJobs(
    String submissionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _jobsApi
          .listSubmissionJobsSubmissionsSubmissionIdJobsGet(
            submissionId: submissionId,
            cancelToken: cancelToken,
          );
      return (response.data ?? const <JobResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Creates and queues this submission's per-question AI 採点 jobs from its
  /// test's confirmed dependency graph, and returns every job the submission
  /// now has (Issue #80 -- nothing in the app called this before, so grading
  /// never started at all).
  ///
  /// Idempotent: called again for a submission that already has jobs under
  /// the active graph version, it creates nothing and hands back the same
  /// list. Throws [SidecarApiException] with [SidecarErrorKind.conflict]
  /// (409) when the test has no confirmed, up-to-date dependency graph, and
  /// also when two callers raced to create the same jobs; the two are not
  /// distinguishable from the response and callers must not try (see
  /// `docs/job-queue.md` 「起票のタイミング」). A 404 (`statusCode`) means the
  /// submission itself is gone, which retrying cannot fix.
  Future<List<JobResponse>> startGrading(
    String submissionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _jobsApi
          .createSubmissionJobsSubmissionsSubmissionIdJobsPost(
            submissionId: submissionId,
            cancelToken: cancelToken,
          );
      return (response.data ?? const <JobResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Requests the annotated-PDF export for [submissionId] (Issue #23).
  /// Refuses with [SidecarErrorKind.conflict] (409) if any question is not
  /// yet confirmed. Otherwise either queues a fresh `Job` (kind EXPORT --
  /// poll [listJobs]/[getJob] for progress, `retryJob` on failure) or, if
  /// the current review state was already exported, hands back that
  /// existing [ExportResponse] directly without queuing anything
  /// (`decision: reuse_existing`).
  Future<ExportRequestResponse> requestExport(
    String submissionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _exportApi
          .requestExportSubmissionsSubmissionIdExportPost(
            submissionId: submissionId,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every successful export recorded for [submissionId], oldest first
  /// (Issue #23: 保存先表示 / export history).
  Future<List<ExportResponse>> listExports(
    String submissionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _exportApi
          .listExportsSubmissionsSubmissionIdExportsGet(
            submissionId: submissionId,
            cancelToken: cancelToken,
          );
      return (response.data ?? const <ExportResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// One `Job`'s current state, by id (Issue #23: polling an export job
  /// without re-listing every job for its submission).
  Future<JobResponse> getJob(String jobId, {CancelToken? cancelToken}) async {
    try {
      final response = await _jobsApi.getJobJobsJobIdGet(
        jobId: jobId,
        cancelToken: cancelToken,
      );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Requeues a `FAILED` job (Issue #23: 出力の再試行).
  Future<JobResponse> retryJob(String jobId, {CancelToken? cancelToken}) async {
    try {
      final response = await _jobsApi.retryJobJobsJobIdRetryPost(
        jobId: jobId,
        cancelToken: cancelToken,
      );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  T _requireBody<T>(Response<T> response) {
    final body = response.data;
    if (body == null) {
      throw SidecarApiException(
        SidecarErrorKind.badResponse,
        'sidecar returned an empty body',
        statusCode: response.statusCode,
      );
    }
    return body;
  }

  DuplicateSubmissionException? _duplicateSubmission(DioException error) {
    if (error.response?.statusCode != 409) return null;
    final detail = error.response?.data is Map
        ? (error.response!.data as Map)['detail']
        : null;
    if (detail is! Map) return null;
    final existingId = detail['existing_submission_id'];
    if (existingId is! String) return null;
    final message = detail['message'];
    return DuplicateSubmissionException(
      message is String ? message : 'duplicate submission',
      existingId,
    );
  }

  /// Release the underlying HTTP connections.
  void close() {
    _dio.close(force: true);
    _uploadDio.close(force: true);
  }

  SidecarApiException _translate(DioException error) {
    switch (error.type) {
      case DioExceptionType.connectionTimeout:
      case DioExceptionType.connectionError:
        // No TCP connection to a loopback port within the budget means the
        // sidecar is not there, not that it is slow.
        return SidecarApiException(
          SidecarErrorKind.unavailable,
          'sidecar is not reachable',
        );
      case DioExceptionType.sendTimeout:
      case DioExceptionType.receiveTimeout:
      case DioExceptionType.transformTimeout:
        return SidecarApiException(
          SidecarErrorKind.timeout,
          'sidecar request timed out',
        );
      case DioExceptionType.cancel:
        return SidecarApiException(
          SidecarErrorKind.cancelled,
          'sidecar request was cancelled',
        );
      case DioExceptionType.badResponse:
        final status = error.response?.statusCode;
        if (status == 401) {
          return SidecarApiException(
            SidecarErrorKind.unauthorized,
            'sidecar rejected the bearer token',
            statusCode: status,
          );
        }
        if (status == 409) {
          return SidecarApiException(
            SidecarErrorKind.conflict,
            _detailMessage(error.response?.data) ??
                'sidecar reported a conflict',
            statusCode: status,
            unconfirmedQuestionIds: _detailQuestionIds(error.response?.data),
          );
        }
        return SidecarApiException(
          SidecarErrorKind.badResponse,
          _detailMessage(error.response?.data) ??
              'sidecar returned HTTP $status',
          statusCode: status,
        );
      case DioExceptionType.badCertificate:
      case DioExceptionType.unknown:
        return SidecarApiException(
          SidecarErrorKind.unknown,
          'unexpected sidecar error',
        );
    }
  }
}

/// FastAPI's `{"detail": "..."}` (or our own `{"detail": {"message": "..."}}`
/// shape for structured errors) -- pulls the human-readable text out so
/// callers see *why* a request failed, not just its status code.
String? _detailMessage(Object? data) {
  if (data is! Map) return null;
  final detail = data['detail'];
  if (detail is String) return detail;
  if (detail is Map && detail['message'] is String) {
    return detail['message'] as String;
  }
  return null;
}

/// `POST .../export`'s 409 body's `detail.question_ids` (Issue #23), or
/// `null` if absent/malformed -- see [SidecarApiException.unconfirmedQuestionIds].
List<String>? _detailQuestionIds(Object? data) {
  if (data is! Map) return null;
  final detail = data['detail'];
  if (detail is! Map) return null;
  final ids = detail['question_ids'];
  if (ids is! List) return null;
  return ids.whereType<String>().toList();
}

String _validatedLoopbackBaseUrl(String value) {
  const message = 'sidecar base URL must be an HTTP loopback URL with a port';
  late final Uri uri;
  try {
    uri = Uri.parse(value);
  } on FormatException {
    throw ArgumentError(message);
  }
  if (uri.scheme != 'http' ||
      uri.host != '127.0.0.1' ||
      !uri.hasPort ||
      (uri.path.isNotEmpty && uri.path != '/') ||
      uri.hasQuery ||
      uri.hasFragment ||
      uri.userInfo.isNotEmpty) {
    throw ArgumentError(message);
  }
  return uri.origin;
}
