/// Single entry point the rest of the app uses to talk to the Python sidecar.
///
/// Innermost layer: it must not import `core` or `features` (see `AGENTS.md`
/// "Architecture" and `docs/technology-stack.md` §5 — `features -> core -> api`).
///
/// It wraps the OpenAPI-generated `auto_scoring_api` client (dio + built_value,
/// regenerated by `pnpm run openapi:generate`) and owns the cross-cutting
/// concerns the generated code leaves to callers: the per-session bearer token,
/// timeouts, cancellation, and collapsing transport failures into one
/// [SidecarApiException].
library;

import 'package:auto_scoring_api/auto_scoring_api.dart';
import 'package:dio/dio.dart';

export 'package:auto_scoring_api/auto_scoring_api.dart'
    show ScoreRequest, ScoreResponse, SubmissionResponse, TestSummary;
export 'package:dio/dio.dart' show CancelToken;

/// Where the sidecar is listening and the token minted for this session.
///
/// Both values come from the sidecar's startup handshake. Process supervision
/// that produces them lands with the Windows distribution work; until then this
/// is constructed by tests.
class SidecarConnection {
  const SidecarConnection({required this.baseUrl, required this.token});

  /// Origin of the sidecar, e.g. `http://127.0.0.1:52348`.
  final String baseUrl;

  /// Per-session bearer token. Never logged.
  final String token;
}

/// What went wrong with a sidecar call, once transport details are stripped.
enum SidecarErrorKind {
  /// The sidecar could not be reached (not started, wrong port, refused).
  unavailable,

  /// The request outlived its timeout.
  timeout,

  /// The caller cancelled the request via a [CancelToken].
  cancelled,

  /// The sidecar rejected the bearer token (HTTP 401).
  unauthorized,

  /// The sidecar answered with an error status or an unreadable body.
  badResponse,

  /// Anything else.
  unknown,
}

/// The only exception callers of [SidecarApiClient] need to handle.
class SidecarApiException implements Exception {
  SidecarApiException(this.kind, this.message, {this.statusCode});

  final SidecarErrorKind kind;
  final String message;
  final int? statusCode;

  @override
  String toString() =>
      'SidecarApiException($kind, "$message", status: $statusCode)';
}

/// Raised by [SidecarApiClient.createSubmission] when the sidecar already has
/// a submission with the same PDF content for this test (409) -- Issue #17's
/// reintake policy (docs/answer-intake-and-preprocessing.md §2). Carries the
/// existing submission id so the UI can point the user at it instead of just
/// showing a generic error.
class DuplicateSubmissionException implements Exception {
  DuplicateSubmissionException(this.message, this.existingSubmissionId);

  final String message;
  final String existingSubmissionId;

  @override
  String toString() =>
      'DuplicateSubmissionException("$message", existing: $existingSubmissionId)';
}

/// Thin, typed boundary over the generated sidecar client.
class SidecarApiClient {
  SidecarApiClient(
    SidecarConnection connection, {
    Duration timeout = const Duration(seconds: 10),
    Duration intakeTimeout = const Duration(minutes: 5),
    Dio? dio,
    Dio? uploadDio,
  }) : _dio = dio ?? Dio(),
       _uploadDio = uploadDio ?? Dio() {
    _configure(_dio, connection, timeout);
    _configure(_uploadDio, connection, intakeTimeout);
    // Pass an empty interceptor list so the generated client does not also
    // register its own auth interceptors on top of ours.
    _api = AutoScoringApi(dio: _dio, interceptors: const []).getDefaultApi();
    _uploadApi = AutoScoringApi(
      dio: _uploadDio,
      interceptors: const [],
    ).getDefaultApi();
  }

  static void _configure(
    Dio dio,
    SidecarConnection connection,
    Duration timeout,
  ) {
    final baseUrl = _validatedLoopbackBaseUrl(connection.baseUrl);
    dio.options
      ..baseUrl = baseUrl
      ..connectTimeout = timeout
      ..sendTimeout = timeout
      ..receiveTimeout = timeout;
    dio.interceptors.add(
      InterceptorsWrapper(
        onRequest: (options, handler) {
          if (options.path != '/healthz') {
            options.headers['Authorization'] = 'Bearer ${connection.token}';
          }
          handler.next(options);
        },
      ),
    );
  }

  final Dio _dio;
  late final DefaultApi _api;

  /// A second Dio/client pair, configured with [intakeTimeout] instead of
  /// [timeout], for [createSubmission]. Rasterizing, deskewing and cropping
  /// every page of a large answer PDF happens inside that one request before
  /// the sidecar responds, so it needs far more headroom than the other
  /// (near-instant) calls share -- otherwise the client reports a timeout
  /// failure while the sidecar keeps working and commits anyway, and a
  /// client-side retry on the same bytes would then just surface as a
  /// confusing duplicate-submission conflict.
  final Dio _uploadDio;
  late final DefaultApi _uploadApi;

  /// Liveness probe. Never throws: an unreachable sidecar is a state the UI
  /// renders, not an error. The endpoint itself needs no auth.
  Future<bool> isHealthy({CancelToken? cancelToken}) async {
    try {
      final response = await _api.healthzHealthzGet(cancelToken: cancelToken);
      return response.data?['status'] == 'ok';
    } on DioException {
      return false;
    }
  }

  /// Score one answer. Throws [SidecarApiException] on any failure.
  Future<ScoreResponse> score({
    required String key,
    required int raw,
    required int maximum,
    CancelToken? cancelToken,
  }) async {
    try {
      final request = ScoreRequest(
        (builder) => builder
          ..key = key
          ..raw = raw
          ..maximum = maximum,
      );
      final response = await _api.scoreScorePost(
        scoreRequest: request,
        cancelToken: cancelToken,
      );
      final body = response.data;
      if (body == null) {
        throw SidecarApiException(
          SidecarErrorKind.badResponse,
          'sidecar returned an empty body',
          statusCode: response.statusCode,
        );
      }
      return body;
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// The registered tests available to import answers into (§16.4 test picker).
  /// Throws [SidecarApiException] on any failure.
  Future<List<TestSummary>> listTests({CancelToken? cancelToken}) async {
    try {
      final response = await _api.listTestsTestsGet(cancelToken: cancelToken);
      return (response.data ?? const <TestSummary>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Every submission imported for [testId], in intake order.
  /// Throws [SidecarApiException] on any failure.
  Future<List<SubmissionResponse>> listSubmissions(
    String testId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _api.listSubmissionsTestsTestIdSubmissionsGet(
        testId: testId,
        cancelToken: cancelToken,
      );
      return (response.data ?? const <SubmissionResponse>[]).toList();
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// One submission's current intake/processing state, for polling progress.
  /// Throws [SidecarApiException] on any failure.
  Future<SubmissionResponse> getSubmission(
    String submissionId, {
    CancelToken? cancelToken,
  }) async {
    try {
      final response = await _api.getSubmissionSubmissionsSubmissionIdGet(
        submissionId: submissionId,
        cancelToken: cancelToken,
      );
      return _requireBody(response);
    } on DioException catch (error) {
      throw _translate(error);
    }
  }

  /// Upload one answer PDF for [testId] (§16.4 答案取込画面). Re-uploading the
  /// same failed submission retries it in place; re-uploading identical bytes
  /// for a submission that is not errored throws
  /// [DuplicateSubmissionException] instead of silently overwriting it
  /// (docs/answer-intake-and-preprocessing.md §2).
  Future<SubmissionResponse> createSubmission({
    required String testId,
    required String filePath,
    String? studentLabel,
    CancelToken? cancelToken,
  }) async {
    try {
      final file = await MultipartFile.fromFile(filePath);
      final response = await _uploadApi
          .createSubmissionTestsTestIdSubmissionsPost(
            testId: testId,
            file: file,
            studentLabel: studentLabel,
            cancelToken: cancelToken,
          );
      return _requireBody(response);
    } on DioException catch (error) {
      final duplicate = _duplicateSubmission(error);
      if (duplicate != null) throw duplicate;
      throw _translate(error);
    }
  }

  T _requireBody<T>(Response<T> response) {
    final body = response.data;
    if (body == null) {
      throw SidecarApiException(
        SidecarErrorKind.badResponse,
        'sidecar returned an empty body',
        statusCode: response.statusCode,
      );
    }
    return body;
  }

  DuplicateSubmissionException? _duplicateSubmission(DioException error) {
    if (error.response?.statusCode != 409) return null;
    final detail = error.response?.data is Map
        ? (error.response!.data as Map)['detail']
        : null;
    if (detail is! Map) return null;
    final existingId = detail['existing_submission_id'];
    if (existingId is! String) return null;
    final message = detail['message'];
    return DuplicateSubmissionException(
      message is String ? message : 'duplicate submission',
      existingId,
    );
  }

  /// Release the underlying HTTP connections.
  void close() {
    _dio.close(force: true);
    _uploadDio.close(force: true);
  }

  SidecarApiException _translate(DioException error) {
    switch (error.type) {
      case DioExceptionType.connectionTimeout:
      case DioExceptionType.connectionError:
        // No TCP connection to a loopback port within the budget means the
        // sidecar is not there, not that it is slow.
        return SidecarApiException(
          SidecarErrorKind.unavailable,
          'sidecar is not reachable',
        );
      case DioExceptionType.sendTimeout:
      case DioExceptionType.receiveTimeout:
      case DioExceptionType.transformTimeout:
        return SidecarApiException(
          SidecarErrorKind.timeout,
          'sidecar request timed out',
        );
      case DioExceptionType.cancel:
        return SidecarApiException(
          SidecarErrorKind.cancelled,
          'sidecar request was cancelled',
        );
      case DioExceptionType.badResponse:
        final status = error.response?.statusCode;
        if (status == 401) {
          return SidecarApiException(
            SidecarErrorKind.unauthorized,
            'sidecar rejected the bearer token',
            statusCode: status,
          );
        }
        return SidecarApiException(
          SidecarErrorKind.badResponse,
          _detailMessage(error.response?.data) ??
              'sidecar returned HTTP $status',
          statusCode: status,
        );
      case DioExceptionType.badCertificate:
      case DioExceptionType.unknown:
        return SidecarApiException(
          SidecarErrorKind.unknown,
          'unexpected sidecar error',
        );
    }
  }
}

/// FastAPI's `{"detail": "..."}` (or our own `{"detail": {"message": "..."}}`
/// shape for structured errors) -- pulls the human-readable text out so
/// callers see *why* a request failed, not just its status code.
String? _detailMessage(Object? data) {
  if (data is! Map) return null;
  final detail = data['detail'];
  if (detail is String) return detail;
  if (detail is Map && detail['message'] is String) {
    return detail['message'] as String;
  }
  return null;
}

String _validatedLoopbackBaseUrl(String value) {
  const message = 'sidecar base URL must be an HTTP loopback URL with a port';
  late final Uri uri;
  try {
    uri = Uri.parse(value);
  } on FormatException {
    throw ArgumentError(message);
  }
  if (uri.scheme != 'http' ||
      uri.host != '127.0.0.1' ||
      !uri.hasPort ||
      (uri.path.isNotEmpty && uri.path != '/') ||
      uri.hasQuery ||
      uri.hasFragment ||
      uri.userInfo.isNotEmpty) {
    throw ArgumentError(message);
  }
  return uri.origin;
}
