[CmdletBinding()]
param(
    [ValidatePattern('^[0-9]+$')]
    [string]$AppId,

    [ValidatePattern('^[0-9]+$')]
    [string]$InstallationId,

    [ValidatePattern('^[A-Za-z0-9-]+$')]
    [string]$AppSlug,

    [string]$PrivateKeyPath,

    [ValidatePattern('^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$')]
    [string]$Repository,

    [ValidatePattern('^[A-Za-z0-9._-]+$')]
    [string]$Remote = 'origin',

    [ValidatePattern('^[0-9]+$')]
    [string]$BotId
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Invoke-Git {
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyCollection()]
        [AllowEmptyString()]
        [string[]]$Arguments
    )

    $output = & git @Arguments 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "git $($Arguments -join ' ') failed:`n$($output -join [Environment]::NewLine)"
    }

    return $output
}

function ConvertTo-ShellSingleQuoted {
    param([Parameter(Mandatory = $true)][string]$Value)

    if ($Value.Contains("'")) {
        throw "Git credential helper arguments cannot contain a single quote: $Value"
    }

    return "'$Value'"
}

function Resolve-Setting {
    param(
        [string]$ProvidedValue,
        [Parameter(Mandatory = $true)][string]$ConfigKey
    )

    if (-not [string]::IsNullOrWhiteSpace($ProvidedValue)) {
        return $ProvidedValue
    }

    $configuredValue = & git config --get $ConfigKey 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($configuredValue)) {
        throw "Missing $ConfigKey. Run the initial setup with all GitHub App parameters."
    }

    return ($configuredValue -join '').Trim()
}

$insideWorkTree = (Invoke-Git -Arguments @('rev-parse', '--is-inside-work-tree')) -join ''
if ($insideWorkTree.Trim() -ne 'true') {
    throw 'Run this script inside the target Git worktree.'
}

$AppId = Resolve-Setting -ProvidedValue $AppId -ConfigKey 'aiagent.githubApp.appId'
$InstallationId = Resolve-Setting -ProvidedValue $InstallationId -ConfigKey 'aiagent.githubApp.installationId'
$AppSlug = Resolve-Setting -ProvidedValue $AppSlug -ConfigKey 'aiagent.githubApp.slug'
$PrivateKeyPath = Resolve-Setting -ProvidedValue $PrivateKeyPath -ConfigKey 'aiagent.githubApp.privateKeyPath'
$Repository = Resolve-Setting -ProvidedValue $Repository -ConfigKey 'aiagent.githubApp.repository'

if ($AppId -notmatch '^[0-9]+$' -or $InstallationId -notmatch '^[0-9]+$' -or $AppSlug -notmatch '^[A-Za-z0-9-]+$') {
    throw 'The stored GitHub App settings are invalid.'
}

if ($Repository -notmatch '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$') {
    throw 'Repository must be in "owner/repo" form. Pass -Repository on the first run.'
}

if (-not (Get-Command pwsh -ErrorAction SilentlyContinue)) {
    throw 'PowerShell 7 (pwsh) is required by the Git credential helper.'
}

$resolvedPrivateKey = (Resolve-Path -LiteralPath $PrivateKeyPath).Path
if ([IO.Path]::GetExtension($resolvedPrivateKey) -ne '.pem') {
    throw 'PrivateKeyPath must point to the .pem file generated by GitHub App settings.'
}

$botLogin = "$AppSlug[bot]"
if ([string]::IsNullOrWhiteSpace($BotId)) {
    $bot = Invoke-RestMethod `
        -Method Get `
        -Uri "https://api.github.com/users/$botLogin" `
        -Headers @{
            Accept = 'application/vnd.github+json'
            'User-Agent' = 'AI-Agent-GitHub-App-Attribution-Setup'
            'X-GitHub-Api-Version' = '2026-03-10'
        }
    $BotId = [string]$bot.id
}

if ($BotId -notmatch '^[0-9]+$') {
    throw "Could not resolve the bot account ID for $botLogin. Install the App on the repository first."
}

$botEmail = "$BotId+$botLogin@users.noreply.github.com"
$pushUrl = "https://github.com/$Repository.git"
$insteadOfKey = "url.$pushUrl.insteadOf"
$sshScpUrl = "git@github.com:$Repository.git"
$sshUrl = "ssh://git@github.com/$Repository.git"
$credentialScript = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot 'github-app-git-credential.ps1')).Path
$helper = @(
    '!pwsh -NoProfile -File'
    (ConvertTo-ShellSingleQuoted $credentialScript)
    '-AppId'
    (ConvertTo-ShellSingleQuoted $AppId)
    '-InstallationId'
    (ConvertTo-ShellSingleQuoted $InstallationId)
    '-PrivateKeyPath'
    (ConvertTo-ShellSingleQuoted $resolvedPrivateKey)
    '-Repository'
    (ConvertTo-ShellSingleQuoted $Repository)
) -join ' '

# Linked worktrees normally share repository config. worktreeConfig keeps the
# App identity and credential helper isolated to the current worktree (e.g. an
# Orca worktree), so other worktrees keep their own identity.
Invoke-Git -Arguments @('config', 'extensions.worktreeConfig', 'true') | Out-Null
Invoke-Git -Arguments @('config', 'aiagent.githubApp.appId', $AppId) | Out-Null
Invoke-Git -Arguments @('config', 'aiagent.githubApp.installationId', $InstallationId) | Out-Null
Invoke-Git -Arguments @('config', 'aiagent.githubApp.slug', $AppSlug) | Out-Null
Invoke-Git -Arguments @('config', 'aiagent.githubApp.privateKeyPath', $resolvedPrivateKey) | Out-Null
Invoke-Git -Arguments @('config', 'aiagent.githubApp.repository', $Repository) | Out-Null
Invoke-Git -Arguments @('config', '--worktree', 'user.name', $botLogin) | Out-Null
Invoke-Git -Arguments @('config', '--worktree', 'user.email', $botEmail) | Out-Null
# A remote URL in the shared repository config is read before a duplicate value
# in config.worktree. Rewrite the repository's common SSH forms instead so the
# effective fetch URL is HTTPS without changing other worktrees.
Invoke-Git -Arguments @('config', '--worktree', '--replace-all', $insteadOfKey, $sshScpUrl) | Out-Null
Invoke-Git -Arguments @('config', '--worktree', '--add', $insteadOfKey, $sshUrl) | Out-Null
Invoke-Git -Arguments @('config', '--worktree', "remote.$Remote.pushurl", $pushUrl) | Out-Null
Invoke-Git -Arguments @('config', '--worktree', 'credential.useHttpPath', 'true') | Out-Null
Invoke-Git -Arguments @('config', '--worktree', 'credential.interactive', 'false') | Out-Null
Invoke-Git -Arguments @('config', '--worktree', '--replace-all', 'credential.helper', '') | Out-Null
Invoke-Git -Arguments @('config', '--worktree', '--add', 'credential.helper', $helper) | Out-Null

$configuredName = ((Invoke-Git -Arguments @('config', '--worktree', '--get', 'user.name')) -join '').Trim()
$configuredEmail = ((Invoke-Git -Arguments @('config', '--worktree', '--get', 'user.email')) -join '').Trim()
$configuredFetchUrl = ((Invoke-Git -Arguments @('remote', 'get-url', $Remote)) -join '').Trim()
$configuredPushUrl = ((Invoke-Git -Arguments @('remote', 'get-url', '--push', $Remote)) -join '').Trim()

if (
    $configuredName -ne $botLogin -or
    $configuredEmail -ne $botEmail -or
    $configuredFetchUrl -ne $pushUrl -or
    $configuredPushUrl -ne $pushUrl
) {
    throw 'The effective worktree attribution settings do not match the GitHub App values.'
}

[PSCustomObject]@{
    Worktree = ((Invoke-Git -Arguments @('rev-parse', '--show-toplevel')) -join '').Trim()
    Author = ((Invoke-Git -Arguments @('var', 'GIT_AUTHOR_IDENT')) -join '').Trim()
    Committer = ((Invoke-Git -Arguments @('var', 'GIT_COMMITTER_IDENT')) -join '').Trim()
    FetchUrl = $configuredFetchUrl
    PushUrl = $configuredPushUrl
    Credential = 'GitHub App installation token generated on demand; token is not stored'
}
